Repository projectcalico/confd, pull requests merged in 2019-10, with the labels that each got.

#273 More Service advertisement tests and cleanup
  pkg/backends/calico/client.go
  pkg/backends/calico/routes.go
  pkg/backends/calico/routes_test.go
  tests/mock_data/calicoctl/mesh/static-routes/input.yaml
  tests/test_suite_common.sh
Labels: docs-not-required, release-note-not-required

#276 Validate clusterIPs and externalIPs before updating
  pkg/backends/calico/routes.go
  pkg/backends/calico/routes_test.go
Labels: cherry-pick-candidate, docs-pr-required, release-note-required

#275 need to harden go mod downloads against network errors
  .fossa.yml
  Makefile
Labels: docs-not-required, release-note-not-required

#277 Cherry-pick into release-v3.10: Validate clusterIPs and externalIPs before updating
  pkg/backends/calico/routes.go
  pkg/backends/calico/routes_test.go
Labels: docs-not-required, release-note-not-required

#280 [release-v3.10] Automatic update of libcalico-go to 399044ecb65942961586f38c38415d95b9122dcc
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#281 Handle empty service IPs in BGP config update
  pkg/backends/calico/client.go
  pkg/backends/calico/routes_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#282 Update client-go to v12.0.0
  glide.lock
  glide.yaml
  pkg/backends/calico/routes.go
Labels: docs-not-required, release-note-not-required

#283 Fix service IPs withdrawal
  pkg/backends/calico/client.go
  pkg/backends/calico/routes_test.go
Labels: docs-not-required, release-note-not-required

#284 Token projection support
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#285 Cut confd test repetition from 5x down to 2x
  tests/test_suite_common.sh
Labels: docs-not-required, release-note-not-required

#287 Remove 'undo' behavior from local_build
  Makefile
Labels: docs-not-required, release-note-not-required
