Repository projectcalico/confd, pull requests merged in 2019-04, with the labels that each got.

#233 Don't use BGP for routes with VXLAN IP pools
  etc/calico/confd/conf.d/tunl-ip.toml
  etc/calico/confd/templates/bird_ipam.cfg.template
  glide.lock
  glide.yaml
  tests/compiled_templates/etcdv3/mesh/vxlan-always/bird.cfg
  tests/compiled_templates/etcdv3/mesh/vxlan-always/bird6.cfg
  tests/compiled_templates/etcdv3/mesh/vxlan-always/bird6_aggr.cfg
  tests/compiled_templates/etcdv3/mesh/vxlan-always/bird6_ipam.cfg
  tests/compiled_templates/etcdv3/mesh/vxlan-always/bird_aggr.cfg
  tests/compiled_templates/etcdv3/mesh/vxlan-always/bird_ipam.cfg
  tests/compiled_templates/kubernetes/mesh/vxlan-always/bird.cfg
  tests/compiled_templates/kubernetes/mesh/vxlan-always/bird6.cfg
  tests/compiled_templates/kubernetes/mesh/vxlan-always/bird6_aggr.cfg
  tests/compiled_templates/kubernetes/mesh/vxlan-always/bird6_ipam.cfg
  tests/compiled_templates/kubernetes/mesh/vxlan-always/bird_aggr.cfg
  tests/compiled_templates/kubernetes/mesh/vxlan-always/bird_ipam.cfg
  tests/mock_data/calicoctl/mesh/vxlan-always/delete.yaml
  tests/mock_data/calicoctl/mesh/vxlan-always/input.yaml
  tests/test_suite_common.sh
Labels: docs-pr-required, release-note-required

#235 [master] Automatic update of libcalico-go to 727a39e77d674af6e7d6684b941916183d80f5de
  glide.lock
Labels: docs-pr-required, release-note-required

#236 [master] Automatic update of libcalico-go to 727a39e77d674af6e7d6684b941916183d80f5de
  glide.lock
  glide.yaml
Labels: docs-pr-required, release-note-required

#237 [master] Automatic update of libcalico-go to 419f1c6419fc7f07ba2dfc536a12e30d69886294
  glide.lock
  glide.yaml
Labels: docs-pr-required, release-note-required

#238 [master] Automatic patch of libcalico-go to 43c1da882b70aba9d0325e7de4393439ef202550
  glide.lock
  glide.yaml
Labels: docs-pr-required, release-note-required

#239 Update libcalico-go to include IPAM changes
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#234 Only update peers if there was a significant change in nodes
  pkg/backends/calico/client.go
Labels: cherry-pick-candidate, docs-not-required, release-note-required

#240 [release-v3.6] Automatic patch of libcalico-go to 24a5a971c54bf0f43417bbfccd0b31e7ffa19a98
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#242 Trigger tunnel address update for VXLAN pools
  etc/calico/confd/templates/tunl-ip.template
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#243 Automated cherry pick of #242: Trigger tunnel address update for VXLAN pools
  etc/calico/confd/templates/tunl-ip.template
Labels: docs-not-required, release-note-not-required

#241 [release-v3.5] Automatic patch of libcalico-go to aae6c757ef3745eb6ecb45351470e66c54fd9e13
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#244 [release-v3.7] Automatic patch of libcalico-go to 6860ff2cfd923a870ff7a76563ce825d6e47adb8
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required
