Repository projectcalico/confd, pull requests merged in 2020-09, with the labels that each got.

#353 Update pins - pick up FelixConfiguration updates
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#355 [release-v3.15] Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#354 [release-v3.16] Update pins
  Makefile
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#356 Semaphore v2 migration / add pin update pipeline
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
  Makefile
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#360 Add BGP password support
  etc/calico/confd/templates/bird.cfg.template
  etc/calico/confd/templates/bird6.cfg.template
  go.mod
  go.sum
  pkg/backends/calico/client.go
  pkg/backends/calico/secret_watcher.go
  tests/compiled_templates/password-deadlock/bird.cfg
  tests/compiled_templates/password-deadlock/bird6.cfg
  tests/compiled_templates/password-deadlock/bird6_aggr.cfg
  tests/compiled_templates/password-deadlock/bird6_ipam.cfg
  tests/compiled_templates/password-deadlock/bird_aggr.cfg
  tests/compiled_templates/password-deadlock/bird_ipam.cfg
  tests/compiled_templates/password/step1/bird.cfg
  tests/compiled_templates/password/step1/bird6.cfg
  tests/compiled_templates/password/step1/bird6_aggr.cfg
  tests/compiled_templates/password/step1/bird6_ipam.cfg
  tests/compiled_templates/password/step1/bird_aggr.cfg
  tests/compiled_templates/password/step1/bird_ipam.cfg
  tests/compiled_templates/password/step2/bird.cfg
  tests/compiled_templates/password/step2/bird6.cfg
  tests/compiled_templates/password/step2/bird6_aggr.cfg
  tests/compiled_templates/password/step2/bird6_ipam.cfg
  tests/compiled_templates/password/step2/bird_aggr.cfg
  tests/compiled_templates/password/step2/bird_ipam.cfg
  tests/compiled_templates/password/step3/bird.cfg
  tests/compiled_templates/password/step3/bird6.cfg
  tests/compiled_templates/password/step3/bird6_aggr.cfg
  tests/compiled_templates/password/step3/bird6_ipam.cfg
  tests/compiled_templates/password/step3/bird_aggr.cfg
  tests/compiled_templates/password/step3/bird_ipam.cfg
  tests/compiled_templates/password/step4/bird.cfg
  tests/compiled_templates/password/step4/bird6.cfg
  tests/compiled_templates/password/step4/bird6_aggr.cfg
  tests/compiled_templates/password/step4/bird6_ipam.cfg
  tests/compiled_templates/password/step4/bird_aggr.cfg
  tests/compiled_templates/password/step4/bird_ipam.cfg
  tests/compiled_templates/password/step5/bird.cfg
  tests/compiled_templates/password/step5/bird6.cfg
  tests/compiled_templates/password/step5/bird6_aggr.cfg
  tests/compiled_templates/password/step5/bird6_ipam.cfg
  tests/compiled_templates/password/step5/bird_aggr.cfg
  tests/compiled_templates/password/step5/bird_ipam.cfg
  tests/compiled_templates/password/step6/bird.cfg
  tests/compiled_templates/password/step6/bird6.cfg
  tests/compiled_templates/password/step6/bird6_aggr.cfg
  tests/compiled_templates/password/step6/bird6_ipam.cfg
  tests/compiled_templates/password/step6/bird_aggr.cfg
  tests/compiled_templates/password/step6/bird_ipam.cfg
  tests/test_suite_common.sh
Labels: docs-pr-required, release-note-required

#363 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
