Repository projectcalico/confd, pull requests merged in 2020-10, with the labels that each got.

#364 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#365 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#366 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#367 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#368 Cherry-pick BGP password support from master
  Makefile
  etc/calico/confd/templates/bird.cfg.template
  etc/calico/confd/templates/bird6.cfg.template
  go.mod
  go.sum
  pkg/backends/calico/client.go
  pkg/backends/calico/secret_watcher.go
  tests/compiled_templates/password-deadlock/bird.cfg
  tests/compiled_templates/password-deadlock/bird6.cfg
  tests/compiled_templates/password-deadlock/bird6_aggr.cfg
  tests/compiled_templates/password-deadlock/bird6_ipam.cfg
  tests/compiled_templates/password-deadlock/bird_aggr.cfg
  tests/compiled_templates/password-deadlock/bird_ipam.cfg
  tests/compiled_templates/password/step1/bird.cfg
  tests/compiled_templates/password/step1/bird6.cfg
  tests/compiled_templates/password/step1/bird6_aggr.cfg
  tests/compiled_templates/password/step1/bird6_ipam.cfg
  tests/compiled_templates/password/step1/bird_aggr.cfg
  tests/compiled_templates/password/step1/bird_ipam.cfg
  tests/compiled_templates/password/step2/bird.cfg
  tests/compiled_templates/password/step2/bird6.cfg
  tests/compiled_templates/password/step2/bird6_aggr.cfg
  tests/compiled_templates/password/step2/bird6_ipam.cfg
  tests/compiled_templates/password/step2/bird_aggr.cfg
  tests/compiled_templates/password/step2/bird_ipam.cfg
  tests/compiled_templates/password/step3/bird.cfg
  tests/compiled_templates/password/step3/bird6.cfg
  tests/compiled_templates/password/step3/bird6_aggr.cfg
  tests/compiled_templates/password/step3/bird6_ipam.cfg
  tests/compiled_templates/password/step3/bird_aggr.cfg
  tests/compiled_templates/password/step3/bird_ipam.cfg
  tests/compiled_templates/password/step4/bird.cfg
  tests/compiled_templates/password/step4/bird6.cfg
  tests/compiled_templates/password/step4/bird6_aggr.cfg
  tests/compiled_templates/password/step4/bird6_ipam.cfg
  tests/compiled_templates/password/step4/bird_aggr.cfg
  tests/compiled_templates/password/step4/bird_ipam.cfg
  tests/compiled_templates/password/step5/bird.cfg
  tests/compiled_templates/password/step5/bird6.cfg
  tests/compiled_templates/password/step5/bird6_aggr.cfg
  tests/compiled_templates/password/step5/bird6_ipam.cfg
  tests/compiled_templates/password/step5/bird_aggr.cfg
  tests/compiled_templates/password/step5/bird_ipam.cfg
  tests/compiled_templates/password/step6/bird.cfg
  tests/compiled_templates/password/step6/bird6.cfg
  tests/compiled_templates/password/step6/bird6_aggr.cfg
  tests/compiled_templates/password/step6/bird6_ipam.cfg
  tests/compiled_templates/password/step6/bird_aggr.cfg
  tests/compiled_templates/password/step6/bird_ipam.cfg
  tests/test_suite_common.sh
Labels: docs-pr-required, release-note-required

#358 Fix: apply keepOriginalNextHop to global peerings as well as node-specific
  etc/calico/confd/templates/bird.cfg.template
  etc/calico/confd/templates/bird6.cfg.template
  tests/compiled_templates/explicit_peering/keepnexthop-global/bird.cfg
  tests/compiled_templates/explicit_peering/keepnexthop-global/bird6.cfg
  tests/compiled_templates/explicit_peering/keepnexthop-global/bird6_aggr.cfg
  tests/compiled_templates/explicit_peering/keepnexthop-global/bird6_ipam.cfg
  tests/compiled_templates/explicit_peering/keepnexthop-global/bird_aggr.cfg
  tests/compiled_templates/explicit_peering/keepnexthop-global/bird_ipam.cfg
  tests/mock_data/calicoctl/explicit_peering/keepnexthop-global/delete.yaml
  tests/mock_data/calicoctl/explicit_peering/keepnexthop-global/input.yaml
  tests/test_suite_common.sh
Labels: docs-not-required, release-note-not-required

#369 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#370 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#372 Added Windows BGP support
  pkg/resource/template/resource.go
  windows-packaging/README-confd.txt
  windows-packaging/conf.d/blocks.toml
  windows-packaging/conf.d/peerings.toml
  windows-packaging/config-bgp.ps1
  windows-packaging/config-bgp.psm1
  windows-packaging/templates/blocks.ps1.template
  windows-packaging/templates/peerings.ps1.template
Labels: docs-pr-required, release-note-required

#379 Export multipath route to kernel on ipv4 and ipv6
  etc/calico/confd/templates/bird.cfg.template
  etc/calico/confd/templates/bird6.cfg.template
  tests/compiled_templates/explicit_peering/global/bird.cfg
  tests/compiled_templates/explicit_peering/global/bird6.cfg
  tests/compiled_templates/explicit_peering/keepnexthop-global/bird.cfg
  tests/compiled_templates/explicit_peering/keepnexthop-global/bird6.cfg
  tests/compiled_templates/explicit_peering/keepnexthop/bird.cfg
  tests/compiled_templates/explicit_peering/keepnexthop/bird6.cfg
  tests/compiled_templates/explicit_peering/route_reflector/bird.cfg
  tests/compiled_templates/explicit_peering/route_reflector/bird6.cfg
  tests/compiled_templates/explicit_peering/selectors/bird.cfg
  tests/compiled_templates/explicit_peering/selectors/bird6.cfg
  tests/compiled_templates/explicit_peering/selectors/step2/bird.cfg
  tests/compiled_templates/explicit_peering/selectors/step2/bird6.cfg
  tests/compiled_templates/explicit_peering/specific_node/bird.cfg
  tests/compiled_templates/explicit_peering/specific_node/bird6.cfg
  tests/compiled_templates/mesh/communities/bird.cfg
  tests/compiled_templates/mesh/communities/bird6.cfg
  tests/compiled_templates/mesh/communities/step2/bird.cfg
  tests/compiled_templates/mesh/communities/step2/bird6.cfg
  tests/compiled_templates/mesh/hash/bird.cfg
  tests/compiled_templates/mesh/hash/bird6.cfg
  tests/compiled_templates/mesh/ipip-always/bird.cfg
  tests/compiled_templates/mesh/ipip-always/bird6.cfg
  tests/compiled_templates/mesh/ipip-cross-subnet/bird.cfg
  tests/compiled_templates/mesh/ipip-cross-subnet/bird6.cfg
  tests/compiled_templates/mesh/ipip-off/bird.cfg
  tests/compiled_templates/mesh/ipip-off/bird6.cfg
  tests/compiled_templates/mesh/static-routes-no-ipv4-address/bird.cfg
  tests/compiled_templates/mesh/static-routes-no-ipv4-address/bird6.cfg
  tests/compiled_templates/mesh/static-routes/bird.cfg
  tests/compiled_templates/mesh/static-routes/bird6.cfg
  tests/compiled_templates/mesh/static-routes/step2/bird.cfg
  tests/compiled_templates/mesh/static-routes/step2/bird6.cfg
  tests/compiled_templates/mesh/vxlan-always/bird.cfg
  tests/compiled_templates/mesh/vxlan-always/bird6.cfg
  tests/compiled_templates/password-deadlock/bird.cfg
  tests/compiled_templates/password-deadlock/bird6.cfg
  tests/compiled_templates/password/step1/bird.cfg
  tests/compiled_templates/password/step1/bird6.cfg
  tests/compiled_templates/password/step2/bird.cfg
  tests/compiled_templates/password/step2/bird6.cfg
  tests/compiled_templates/password/step3/bird.cfg
  tests/compiled_templates/password/step3/bird6.cfg
  tests/compiled_templates/password/step4/bird.cfg
  tests/compiled_templates/password/step4/bird6.cfg
  tests/compiled_templates/password/step5/bird.cfg
  tests/compiled_templates/password/step5/bird6.cfg
  tests/compiled_templates/password/step6/bird.cfg
  tests/compiled_templates/password/step6/bird6.cfg
Labels: docs-pr-required, release-note-required

#381 Upgrade to golang 1.15
  Makefile
  go.mod
Labels: docs-not-required, release-note-not-required

#382 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#383 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
