Repository projectcalico/confd, pull requests merged in 2020-01, with the labels that each got.

#306 release-v3.10 - Update libcalico-go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#305 release-v3.9 - Update libcalico-go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#304 release-v3.8 - Update libcalico-go
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#307 Update pins and only require go 1.12 for now
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#311 Don't prevent mesh peerings when routeReflectorClusterID is defined
  etc/calico/confd/templates/bird.cfg.template
  tests/compiled_templates/explicit_peering/route_reflector/bird.cfg
Labels: docs-not-required, release-note-required
