Repository projectcalico/confd, pull requests merged in 2020-12, with the labels that each got.

#404 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#405 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#406 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#409 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#411 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#410 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#412 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#414 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#413 Add support for BGPPeer SourceAddress field
  etc/calico/confd/templates/bird.cfg.template
  etc/calico/confd/templates/bird6.cfg.template
  pkg/backends/calico/client.go
  tests/compiled_templates/explicit_peering/global/bird.cfg
  tests/compiled_templates/explicit_peering/keepnexthop-global/bird.cfg
  tests/compiled_templates/explicit_peering/keepnexthop-global/bird6.cfg
  tests/compiled_templates/explicit_peering/keepnexthop/bird.cfg
  tests/compiled_templates/explicit_peering/keepnexthop/bird6.cfg
  tests/compiled_templates/explicit_peering/route_reflector/bird.cfg
  tests/compiled_templates/explicit_peering/route_reflector/bird6.cfg
  tests/compiled_templates/explicit_peering/selectors/bird.cfg
  tests/compiled_templates/explicit_peering/selectors/bird6.cfg
  tests/compiled_templates/explicit_peering/selectors/step2/bird.cfg
  tests/compiled_templates/explicit_peering/selectors/step2/bird6.cfg
  tests/compiled_templates/explicit_peering/specific_node/bird.cfg
  tests/compiled_templates/mesh/communities/bird.cfg
  tests/compiled_templates/mesh/communities/step2/bird.cfg
  tests/compiled_templates/mesh/hash/bird.cfg
  tests/compiled_templates/mesh/ipip-always/bird.cfg
  tests/compiled_templates/mesh/ipip-cross-subnet/bird.cfg
  tests/compiled_templates/mesh/ipip-off/bird.cfg
  tests/compiled_templates/mesh/ipip-off/bird6.cfg
  tests/compiled_templates/mesh/static-routes/bird.cfg
  tests/compiled_templates/mesh/static-routes/bird6.cfg
  tests/compiled_templates/mesh/static-routes/step2/bird.cfg
  tests/compiled_templates/mesh/static-routes/step2/bird6.cfg
  tests/compiled_templates/mesh/vxlan-always/bird.cfg
  tests/compiled_templates/password-deadlock/bird.cfg
  tests/compiled_templates/password/step1/bird.cfg
  tests/compiled_templates/password/step2/bird.cfg
  tests/compiled_templates/password/step3/bird.cfg
  tests/compiled_templates/password/step4/bird.cfg
  tests/compiled_templates/password/step5/bird.cfg
  tests/compiled_templates/password/step6/bird.cfg
  tests/mock_data/calicoctl/explicit_peering/global/input.yaml
Labels: docs-pr-required, release-note-not-required

#416 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#417 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#418 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#415 Revert test diff loosening, now that community values are sorted
  tests/test_suite_common.sh
Labels: docs-not-required, release-note-not-required

#421 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
