Repository projectcalico/confd, pull requests merged in 2020-08, with the labels that each got.

#348 Add clean to ci target
  Makefile
Labels: docs-pr-required, release-note-required

#339 New feature for maintaining original next hop on specific bgppeer
  etc/calico/confd/templates/bird.cfg.template
  etc/calico/confd/templates/bird6.cfg.template
  pkg/backends/calico/client.go
  tests/compiled_templates/explicit_peering/keepnexthop/bird.cfg
  tests/compiled_templates/explicit_peering/keepnexthop/bird6.cfg
  tests/compiled_templates/explicit_peering/keepnexthop/bird6_aggr.cfg
  tests/compiled_templates/explicit_peering/keepnexthop/bird6_ipam.cfg
  tests/compiled_templates/explicit_peering/keepnexthop/bird_aggr.cfg
  tests/compiled_templates/explicit_peering/keepnexthop/bird_ipam.cfg
  tests/mock_data/calicoctl/explicit_peering/keepnexthop/delete.yaml
  tests/mock_data/calicoctl/explicit_peering/keepnexthop/input.yaml
  tests/test_suite_common.sh
Labels: docs-completed, release-note-not-required

#349 Pin libcalico-go to release-v3.16.
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#350 Update pins
  Makefile
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#351 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#352 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required
