Repository projectcalico/confd, pull requests merged in 2020-07, with the labels that each got.

#336 Revert "Program blackhole routes for full rejectcidrs to avoid route loops"
  etc/calico/confd/templates/bird6_ipam.cfg.template
  etc/calico/confd/templates/bird_ipam.cfg.template
  tests/compiled_templates/mesh/static-routes-no-ipv4-address/bird_ipam.cfg
  tests/compiled_templates/mesh/static-routes/bird6_ipam.cfg
  tests/compiled_templates/mesh/static-routes/bird_ipam.cfg
Labels: docs-not-required, release-note-not-required

#337 Automated cherry pick of #336: Revert "Program blackhole routes for full rejectcidrs to
  etc/calico/confd/templates/bird6_ipam.cfg.template
  etc/calico/confd/templates/bird_ipam.cfg.template
  tests/compiled_templates/mesh/static-routes-no-ipv4-address/bird_ipam.cfg
  tests/compiled_templates/mesh/static-routes/bird6_ipam.cfg
  tests/compiled_templates/mesh/static-routes/bird_ipam.cfg
Labels: docs-not-required, release-note-required

#347 Upgrade to Golang 1.14
  Makefile
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#346 Avoid duplicate communities in BIRD
  pkg/backends/calico/client.go
  tests/mock_data/calicoctl/mesh/communities/input.yaml
  tests/mock_data/calicoctl/mesh/communities/step2/input.yaml
  tests/test_suite_common.sh
Labels: docs-pr-required, release-note-required
