Repository projectcalico/confd, pull requests merged in 2021-06, with the labels that each got.

#523 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#524 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#525 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#527 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#526 Fix sem timeouts and priorities
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
Labels: docs-pr-required, release-note-required

#528 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#530 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#531 Fix sem timeouts and priorities
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
Labels: docs-pr-required, release-note-required

#532 Replace lib/v3 package with projectcalico/api
  go.mod
  go.sum
  pkg/backends/calico/client.go
Labels: docs-not-required, merge-when-ready, release-note-not-required

#533 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#534 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#535 Update api pins on pin update
  Makefile
Labels: docs-not-required, release-note-not-required

#537 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#538 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#539 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#540 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#541 [v3.18 pick concurrency 942eab8
  pkg/backends/calico/client.go
  pkg/backends/calico/node_labels.go
Labels: docs-not-required, release-note-not-required
