Repository projectcalico/confd, pull requests merged in 2021-03, with the labels that each got.

#450 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#451 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#454 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#458 Update pins
  go.mod
  go.sum
  tests/compiled_templates/explicit_peering/keepnexthop-global/bird_aggr.cfg
  tests/compiled_templates/explicit_peering/keepnexthop/bird_aggr.cfg
  tests/compiled_templates/explicit_peering/selectors/step2/bird_aggr.cfg
  tests/compiled_templates/mesh/communities/bird_aggr.cfg
  tests/compiled_templates/mesh/communities/step2/bird_aggr.cfg
  tests/compiled_templates/mesh/static-routes-exclude-node/bird_aggr.cfg
  tests/compiled_templates/mesh/static-routes-exclude-node/step2/bird_aggr.cfg
  tests/compiled_templates/mesh/static-routes/step2/bird_aggr.cfg
Labels: docs-pr-required, release-note-required

#459 Fix tests
  tests/compiled_templates/explicit_peering/keepnexthop-global/bird_aggr.cfg
  tests/compiled_templates/explicit_peering/keepnexthop/bird_aggr.cfg
  tests/compiled_templates/explicit_peering/selectors/step2/bird_aggr.cfg
  tests/compiled_templates/mesh/communities/bird_aggr.cfg
  tests/compiled_templates/mesh/communities/step2/bird_aggr.cfg
  tests/compiled_templates/mesh/static-routes-exclude-node/bird_aggr.cfg
  tests/compiled_templates/mesh/static-routes-exclude-node/step2/bird_aggr.cfg
  tests/compiled_templates/mesh/static-routes/step2/bird_aggr.cfg
Labels: docs-pr-required, release-note-required

#469 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#470 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#471 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#472 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#473 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#475 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#477 Update pins
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#476 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#478 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#479 Fix concurrent access error for node label cache
  pkg/backends/calico/client.go
  pkg/backends/calico/node_labels.go
Labels: docs-pr-required, release-note-required

#480 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#481 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#482 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#483 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required
