Repository projectcalico/confd, pull requests merged in 2021-01, with the labels that each got.

#423 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#422 Advertise LoadBalancer IPs
  pkg/backends/calico/client.go
  pkg/backends/calico/routes.go
  tests/compiled_templates/mesh/static-routes/bird_aggr.cfg
  tests/compiled_templates/mesh/static-routes/bird_ipam.cfg
  tests/mock_data/calicoctl/mesh/static-routes/input.yaml
  tests/mock_data/calicoctl/mesh/static-routes/kubectl-input.yaml
Labels: docs-pr-required, release-note-required

#420 Don't advertise services from nodes with exclude-loadbalancer label
  pkg/backends/calico/client.go
  pkg/backends/calico/routes.go
  tests/compiled_templates/mesh/static-routes-exclude-node/bird.cfg
  tests/compiled_templates/mesh/static-routes-exclude-node/bird6.cfg
  tests/compiled_templates/mesh/static-routes-exclude-node/bird6_aggr.cfg
  tests/compiled_templates/mesh/static-routes-exclude-node/bird6_ipam.cfg
  tests/compiled_templates/mesh/static-routes-exclude-node/bird_aggr.cfg
  tests/compiled_templates/mesh/static-routes-exclude-node/bird_ipam.cfg
  tests/compiled_templates/mesh/static-routes-exclude-node/step2/bird.cfg
  tests/compiled_templates/mesh/static-routes-exclude-node/step2/bird6.cfg
  tests/compiled_templates/mesh/static-routes-exclude-node/step2/bird6_aggr.cfg
  tests/compiled_templates/mesh/static-routes-exclude-node/step2/bird6_ipam.cfg
  tests/compiled_templates/mesh/static-routes-exclude-node/step2/bird_aggr.cfg
  tests/compiled_templates/mesh/static-routes-exclude-node/step2/bird_ipam.cfg
  tests/mock_data/calicoctl/mesh/static-routes-exclude-node/delete.yaml
  tests/mock_data/calicoctl/mesh/static-routes-exclude-node/input.yaml
  tests/mock_data/calicoctl/mesh/static-routes-exclude-node/kubectl-delete.yaml
  tests/mock_data/calicoctl/mesh/static-routes-exclude-node/kubectl-input.yaml
  tests/mock_data/calicoctl/mesh/static-routes-exclude-node/step2/input.yaml
  tests/test_suite_common.sh
Labels: docs-pr-required, release-note-required

#330 Fix blackhole cause ipam failed with /32 blocksize
  etc/calico/confd/templates/bird6_aggr.cfg.template
  etc/calico/confd/templates/bird_aggr.cfg.template
  pkg/resource/template/template_funcs.go
  tests/compiled_templates/explicit_peering/global/bird_aggr.cfg
  tests/compiled_templates/explicit_peering/route_reflector/bird_aggr.cfg
  tests/compiled_templates/explicit_peering/selectors/bird_aggr.cfg
  tests/compiled_templates/explicit_peering/specific_node/bird_aggr.cfg
  tests/compiled_templates/mesh/hash/bird_aggr.cfg
  tests/compiled_templates/mesh/ipip-always/bird_aggr.cfg
  tests/compiled_templates/mesh/ipip-cross-subnet/bird_aggr.cfg
  tests/compiled_templates/mesh/ipip-off/bird_aggr.cfg
  tests/compiled_templates/mesh/static-routes-no-ipv4-address/bird_aggr.cfg
  tests/compiled_templates/mesh/static-routes/bird_aggr.cfg
  tests/compiled_templates/mesh/vxlan-always/bird_aggr.cfg
  tests/mock_data/etcd/block
  tests/mock_data/kdd/ipam.yaml
Labels: docs-not-required, release-note-required
